<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> Votre guide d'ouvrage et des données télévisuels </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="said.css">
</head>

<body>
    <nav>

        <h1>Vise Up</h1>

        <div class="onglets">

            <a href="http://localhost/pfa2/abcdef/monProjet/P2.php">Se connecter</a>
            <a href="http://localhost/pfa2/abcdef/monProjet/pageinscription.php">S'inscrire</a>
        </div>
    </nav>

    <header>
        <h1>RELAXEZ VOUS ,</h1>
        <h4>Avec les meilleurs films,série... selon vos choix.</h4>


        <a href=#DESCRIPTION> Savoir plus sur le site.. </a>

    </header>

    <section class="main" id="DESCRIPTION">

        <div class="content">
            <div class="card">
                <div class="left">
                    <h1>OBJECTIFS</h1>
                    <p>Recomander des romans,des séries ,des animes,des films</p>
                </div>
                <div class="right">
                    <img src="https://i.ytimg.com/vi/gQ8EONrrCRE/maxresdefault.jpg" width="300" height="300" alt="">
                    <style>
                        img {
                            border-radius: 50%;
                        }
                    </style>
                </div>
            </div>

            <div class="card">
                <div class="left">
                    <h1>Nos propositions concernant ce qui s'affiche</h1>
                    <p>Les propositions seront affiché selon le centre d'intérets du chère utilisateur apres son authentification au site web </p>
                </div>
                <div class="right">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Books_HD_%288314929977%29.jpg/800px-Books_HD_%288314929977%29.jpg" width="300" height="300" alt="">

                    <style>
                        img {
                            border-radius: 50%;
                        }
                    </style>
                </div>
            </div>
        </div>
    </section>
</body>

</html>